# -*- coding: utf-8 -*-
"""thg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18YK8bTqMyC0ozMdX-qqHqGMqoS3QMSU2
"""

word = input("Введите слово: ")
for letter in word:
    print(letter)

import time

def date():
    """
    Возвращает текущую дату и время в формате 'ДД.ММ.ГГГГ, ЧЧ:ММ'.
    """
    c_time = time.localtime()
    f_time = time.strftime("%d.%m.%Y, %H:%M", c_time)
    return f"Текущая дата и время: {f_time}"